use_frameworks!

target 'ETiOSToolbox_Example', :exclusive => true do
  pod 'ETiOSToolbox', :path => '../'
end

target 'ETiOSToolbox_Tests', :exclusive => true do
  pod 'ETiOSToolbox', :path => '../'

  
end
